# Generated by Django 6.0.3 on 2026-04-06 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holisticmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holisticmap.company')),
            ],
        ),
        migrations.CreateModel(
            name='RoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holisticmap.role')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holisticmap.skill')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='skills',
            field=models.ManyToManyField(through='holisticmap.RoleSkill', to='holisticmap.skill'),
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holisticmap.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holisticmap.skill')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(through='holisticmap.EmployeeSkill', to='holisticmap.skill'),
        ),
    ]
