# Generated by Django 6.0.3 on 2026-04-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holisticmap', '0002_skill_role_roleskill_role_skills_employeeskill_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeskill',
            unique_together={('employee', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='roleskill',
            unique_together={('role', 'skill')},
        ),
    ]
