# Generated by Django 6.0.3 on 2026-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holisticmap', '0004_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='join_secret_hash',
            new_name='employee_secret_hash',
        ),
        migrations.AddField(
            model_name='company',
            name='employer_secret_hash',
            field=models.CharField(default='temp_secret', max_length=255),
            preserve_default=False,
        ),
    ]
