# Generated by Django 6.0.4 on 2026-04-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holisticmap', '0006_add_user_links_strict'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleskill',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
