# Generated by Django 6.0.4 on 2026-04-27 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holisticmap', '0007_roleskill_is_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holisticmap.education')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holisticmap.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RoleEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holisticmap.education')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holisticmap.role')),
            ],
            options={
                'unique_together': {('role', 'education')},
            },
        ),
    ]
