# Generated by Django 6.0.4 on 2026-05-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holisticmap', '0008_education_employeeeducation_roleeducation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeeducation',
            unique_together={('employee', 'education')},
        ),
    ]
