# Generated by Django 6.0.4 on 2026-05-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holisticmap', '0009_alter_employeeeducation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskill',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roleskill',
            name='min_years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
