# Generated by Django 6.0.4 on 2026-05-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holisticmap', '0010_employeeskill_years_experience_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roleskill',
            unique_together={('role', 'skill', 'is_required')},
        ),
    ]
